### ISSUE TITLE
cleanup commit in urbach/hadron breaks onlinemeas

### ISSUE THREAD

**Issue by kostrzewa** [etmc/hadron#12]
The removal of getCor (cfunction.R) breaks some functionality. While I use this functionality regularly, maybe it would be better if I rewrite onlinemeas (or move away from it in my analysis routines). What do you think?

**Comment by kostrzewa** [comment]
6ef3c9fc5c47180a74e608ee471266afe07aaffe

**Comment by kostrzewa** [comment]
@urbach this also breaks the computation of bootstrap errors...  I think we either need to fix this, or I need to take a (few) day(s) off to rewrite and improve the HMC analysis code...

**Comment by urbach** [comment]
> @urbach this also breaks the computation of bootstrap errors...  I think we either need to fix this, or I need to take a (few) day(s) off to rewrite and improve the HMC analysis code...

I should fix it...!

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/hadron/issues/12#issuecomment-279731903
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by urbach** [comment]
okay, first of all I have added 'getCor' back in

**Comment by urbach** [comment]
> @urbach this also breaks the computation of bootstrap errors...  

what exactly do you mean with breaks the computation of bootstrap errors?

--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by urbach** [comment]
@kostrzewa I think I have fixed this now in my `master` branch, could you confirm!?

**Comment by kostrzewa** [comment]
> what exactly do you mean with breaks the computation of bootstrap errors?

I was referring to onlinemeas with bootstrap errors (in addition to or instead of uwerr)

> I think I have fixed this now in my master branch, could you confirm!?

I'll take a look, shouldn't be long.

**Comment by kostrzewa** [comment]
In your master, could you also add ```getorderedconfignumbers``` to the exported functions? I read the online correlators directly now, which is somewhat slow, but it doesn't require the intermediate stage of ```putonlinetogether.sh```. Down the line, it might be worth investigating if the concatenation can be done efficiently from within R.

**Comment by urbach** [comment]
done

--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
Works perfectly, thanks!
