### ISSUE TITLE
Please specify license version

### ISSUE THREAD

**Issue by martin-ueding** [etmc/hadron#15]
The file `DESCRIPTION` states that the license is GPL but it does not state which version. So it could be either of

- GPL 2
- GPL 2 or later
- GPL 3
- GPL or later

I'd like to make a Fedora package from this package, but I would need to know the exact license in order to correctly package it.

**Comment by urbach** [comment]
fixed in urbach/hadron. Please use urbach/hadron for the most up-to-date package. etmc/hadron will be refreshed on a much less frequent timescale.
