### ISSUE TITLE
documentation for bootstrap.effectivemass contains error

### ISSUE THREAD

**Issue by kostrzewa** [etmc/hadron#21]
```bootstrap.effectivemass``` doc mentions ```subtracted``` type, this should be ```shifted``` throughout

**Comment by urbach** [comment]
> ```bootstrap.effectivemass``` doc mentions ```subtracted``` type, this should be ```shifted``` throughout

fixed

--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu
